/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirstguicalculator;

import myfirstguicalculator.calculatorclasses.Calculator;

/**
 *
 * @author sangr
 */
public class GuiCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GuiCalculator
     */
    public GuiCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberOne = new java.awt.Button();
        output = new java.awt.Label();
        numberTwo = new java.awt.Button();
        numberThree = new java.awt.Button();
        numberFive = new java.awt.Button();
        numberSix = new java.awt.Button();
        numberSeven = new java.awt.Button();
        numberEight = new java.awt.Button();
        numberNine = new java.awt.Button();
        numberFour = new java.awt.Button();
        numberZero = new java.awt.Button();
        symbolResult = new java.awt.Button();
        symbolPlus = new java.awt.Button();
        symbolMinus = new java.awt.Button();
        symbolProduct = new java.awt.Button();
        symbolDivide = new java.awt.Button();
        symbolOpeningBraces = new java.awt.Button();
        symbolClosingBraces = new java.awt.Button();
        clear = new java.awt.Button();
        backspace = new java.awt.Button();
        input = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numberOne.setActionCommand("numberOne");
        numberOne.setBackground(new java.awt.Color(0, 204, 153));
        numberOne.setLabel("1");
        numberOne.setName("buttonOne"); // NOI18N
        numberOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneActionPerformed(evt);
            }
        });

        output.setAlignment(java.awt.Label.RIGHT);
        output.setBackground(new java.awt.Color(51, 255, 0));
        output.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        output.setForeground(new java.awt.Color(255, 255, 255));
        output.setName("output"); // NOI18N
        output.setText("0");

        numberTwo.setActionCommand("numberTwo");
        numberTwo.setBackground(new java.awt.Color(0, 204, 153));
        numberTwo.setLabel("2");
        numberTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTwoActionPerformed(evt);
            }
        });

        numberThree.setActionCommand("numberThree");
        numberThree.setBackground(new java.awt.Color(0, 204, 153));
        numberThree.setLabel("3");
        numberThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberThreeActionPerformed(evt);
            }
        });

        numberFive.setActionCommand("numberFive");
        numberFive.setBackground(new java.awt.Color(0, 204, 153));
        numberFive.setLabel("5");
        numberFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFiveActionPerformed(evt);
            }
        });

        numberSix.setActionCommand("numberSix");
        numberSix.setBackground(new java.awt.Color(0, 204, 153));
        numberSix.setLabel("6");
        numberSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSixActionPerformed(evt);
            }
        });

        numberSeven.setActionCommand("numberSeven");
        numberSeven.setBackground(new java.awt.Color(0, 204, 153));
        numberSeven.setLabel("7");
        numberSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSevenActionPerformed(evt);
            }
        });

        numberEight.setActionCommand("numberEight");
        numberEight.setBackground(new java.awt.Color(0, 204, 153));
        numberEight.setLabel("8");
        numberEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberEightActionPerformed(evt);
            }
        });

        numberNine.setActionCommand("numberNine");
        numberNine.setBackground(new java.awt.Color(0, 204, 153));
        numberNine.setLabel("9");
        numberNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberNineActionPerformed(evt);
            }
        });

        numberFour.setActionCommand("numberFour");
        numberFour.setBackground(new java.awt.Color(0, 204, 153));
        numberFour.setLabel("4");
        numberFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFourActionPerformed(evt);
            }
        });

        numberZero.setActionCommand("numberZero");
        numberZero.setBackground(new java.awt.Color(0, 204, 153));
        numberZero.setLabel("0");
        numberZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberZeroActionPerformed(evt);
            }
        });

        symbolResult.setActionCommand("result");
        symbolResult.setBackground(new java.awt.Color(0, 204, 153));
        symbolResult.setLabel("=");
        symbolResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolResultActionPerformed(evt);
            }
        });

        symbolPlus.setActionCommand("symbolPlus");
        symbolPlus.setBackground(new java.awt.Color(0, 204, 153));
        symbolPlus.setLabel("+");
        symbolPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolPlusActionPerformed(evt);
            }
        });

        symbolMinus.setActionCommand("symbolMinus");
        symbolMinus.setBackground(new java.awt.Color(0, 204, 153));
        symbolMinus.setLabel("-");
        symbolMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolMinusActionPerformed(evt);
            }
        });

        symbolProduct.setActionCommand("symbolProduct");
        symbolProduct.setBackground(new java.awt.Color(0, 204, 153));
        symbolProduct.setLabel("x");
        symbolProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolProductActionPerformed(evt);
            }
        });

        symbolDivide.setActionCommand("symbolDivide");
        symbolDivide.setBackground(new java.awt.Color(0, 204, 153));
        symbolDivide.setLabel("/");
        symbolDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolDivideActionPerformed(evt);
            }
        });

        symbolOpeningBraces.setActionCommand("openingBraces");
        symbolOpeningBraces.setBackground(new java.awt.Color(0, 204, 153));
        symbolOpeningBraces.setLabel("(");
        symbolOpeningBraces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolOpeningBracesActionPerformed(evt);
            }
        });

        symbolClosingBraces.setActionCommand("closingBraces");
        symbolClosingBraces.setBackground(new java.awt.Color(0, 204, 153));
        symbolClosingBraces.setLabel(")");
        symbolClosingBraces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolClosingBracesActionPerformed(evt);
            }
        });

        clear.setActionCommand("clear");
        clear.setBackground(new java.awt.Color(51, 51, 255));
        clear.setLabel("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        backspace.setActionCommand("backSpace");
        backspace.setBackground(new java.awt.Color(255, 51, 51));
        backspace.setLabel("Backspace");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        input.setName("input"); // NOI18N
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(symbolPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(symbolMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(numberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(symbolClosingBraces, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(symbolProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(symbolDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(symbolResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(backspace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(330, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(symbolOpeningBraces, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backspace, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(numberThree, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(numberFour, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(numberOne, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(symbolResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(numberNine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(symbolDivide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(symbolProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(symbolMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addComponent(symbolPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(symbolClosingBraces, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(symbolOpeningBraces, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        output.getAccessibleContext().setAccessibleName("output");
        output.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneActionPerformed
        this.input.setText(input.getText()+"1");
    }//GEN-LAST:event_numberOneActionPerformed

    private void numberTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTwoActionPerformed
        this.input.setText(input.getText()+"2");
    }//GEN-LAST:event_numberTwoActionPerformed

    private void numberThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberThreeActionPerformed
        this.input.setText(input.getText()+"3");
    }//GEN-LAST:event_numberThreeActionPerformed

    private void numberFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFiveActionPerformed
        this.input.setText(input.getText()+"5");
    }//GEN-LAST:event_numberFiveActionPerformed

    private void numberSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSixActionPerformed
        this.input.setText(input.getText()+"6");
    }//GEN-LAST:event_numberSixActionPerformed

    private void numberSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSevenActionPerformed
        this.input.setText(input.getText()+"7");
    }//GEN-LAST:event_numberSevenActionPerformed

    private void numberEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberEightActionPerformed
        this.input.setText(input.getText()+"8");
    }//GEN-LAST:event_numberEightActionPerformed

    private void numberNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberNineActionPerformed
        this.input.setText(input.getText()+"9");
    }//GEN-LAST:event_numberNineActionPerformed

    private void numberFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFourActionPerformed
        this.input.setText(input.getText()+"4");
    }//GEN-LAST:event_numberFourActionPerformed

    private void numberZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberZeroActionPerformed
        this.input.setText(input.getText()+"0");
    }//GEN-LAST:event_numberZeroActionPerformed

    private void symbolResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolResultActionPerformed
        String expression = this.input.getText();
        Calculator calculator = new Calculator();
        double result = calculator.calculate(expression);
        this.output.setText(Double.toString(result));
    }//GEN-LAST:event_symbolResultActionPerformed

    private void symbolPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolPlusActionPerformed
        this.input.setText(input.getText()+"+");
    }//GEN-LAST:event_symbolPlusActionPerformed

    private void symbolMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolMinusActionPerformed
        this.input.setText(input.getText()+"-");
    }//GEN-LAST:event_symbolMinusActionPerformed

    private void symbolProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolProductActionPerformed
        this.input.setText(input.getText()+"*");
    }//GEN-LAST:event_symbolProductActionPerformed

    private void symbolDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolDivideActionPerformed
        this.input.setText(input.getText()+"/");
    }//GEN-LAST:event_symbolDivideActionPerformed

    private void symbolOpeningBracesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolOpeningBracesActionPerformed
        this.input.setText(input.getText()+"(");
    }//GEN-LAST:event_symbolOpeningBracesActionPerformed

    private void symbolClosingBracesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolClosingBracesActionPerformed
        this.input.setText(input.getText()+")");
    }//GEN-LAST:event_symbolClosingBracesActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        input.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        try{
            String currentText = input.getText();
        String newText = currentText.substring(0, currentText.length()-1);
        input.setText(newText);
        }
        catch(StringIndexOutOfBoundsException e){
            input.setText("");
        }
    }//GEN-LAST:event_backspaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button backspace;
    private java.awt.Button clear;
    private java.awt.TextField input;
    private java.awt.Button numberEight;
    private java.awt.Button numberFive;
    private java.awt.Button numberFour;
    private java.awt.Button numberNine;
    private java.awt.Button numberOne;
    private java.awt.Button numberSeven;
    private java.awt.Button numberSix;
    private java.awt.Button numberThree;
    private java.awt.Button numberTwo;
    private java.awt.Button numberZero;
    private java.awt.Label output;
    private java.awt.Button symbolClosingBraces;
    private java.awt.Button symbolDivide;
    private java.awt.Button symbolMinus;
    private java.awt.Button symbolOpeningBraces;
    private java.awt.Button symbolPlus;
    private java.awt.Button symbolProduct;
    private java.awt.Button symbolResult;
    // End of variables declaration//GEN-END:variables
}
